name: dcgm-exporter
base: core20 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: NVidia DCGM exporter
description: |
  Snapped DGCM exporter

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts: 
  dcgm-exporter:
    # See 'snapcraft plugins'
    plugin: go
    source: .
    source-subdir: pkg

apps:
  dcgm-exporter:
    command: bin/dcgm-exporter
